## Setup

In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
# from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [2]:
from dotenv import load_dotenv

load_dotenv()

False

In [38]:
import pandas as pd
books= pd.read_csv('book_cleaned.csv')
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,embedding_input,book_id
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Gilead A NOVEL THAT READERS and critics have b...,9780002005883
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Spider's Web: A Novel A new 'Christie for Chri...,9780002261982
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...","Rage of angels A memorable, mesmerizing heroin...",9780006178736
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,The Four Loves Lewis' work on the nature of lo...,9780006280897
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...","The Problem of Pain ""In The Problem of Pain, C...",9780006280934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Mistaken Identity On A Train Journey Home To N...,9788172235222
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,Journey to the East This book tells the tale o...,9788173031014
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,I Am that: Talks with Sri Nisargadatta Maharaj...,9788185300535
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,The Berlin Phenomenology Since the three volum...,9789027712059

In [4]:
books['description']

0       A NOVEL THAT READERS and critics have been eag...
1       A new 'Christie for Christmas' -- a full-lengt...
2       A memorable, mesmerizing heroine Jennifer -- b...
3       Lewis' work on the nature of love divides love...
4       "In The Problem of Pain, C.S. Lewis, one of th...
                              ...
5192    On A Train Journey Home To North India After L...
5193    This book tells the tale of a man who goes on ...
5194    Wisdom to Create a Life of Passion, Purpose, a...
5195    This collection of the timeless teachings of o...
5196    Since the three volume edition ofHegel's Philo...
Name: description, Length: 5197, dtype: str

## Splitting the books using CharacterTextSplitter

In [5]:
# Creating text document for CharacterTextSplitter

books['tagged_description'].to_csv('tagged_description.txt',
                                   index=False,
                                   header=False)

In [6]:
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=1, chunk_overlap=0, separator='\n')
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 375, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 483, which is longer than the specified 1
Created a chunk of size 484, which is longer than the specified 1
Created a chunk of size 962, which is longer than the specified 1
Created a chunk of size 188, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1
Created a chunk of size 296, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 881, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 213, which is longer than the specified 1
Created a chunk of size 216, which is longer than the specified 1
Created a chunk of size 515, which is longer than the specified 1
Created a chunk of size 754, which is longer than the specified 1
Created a chunk of size 390, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 253, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 730, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 258, which is longer than the specified 1
Created a chunk of size 475, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 1267, which is longer than the specified 1
Created a chunk of size 683, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 555, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 282, which is longer than the specified 1
Created a chunk of size 789, which is longer than the specified 1
Created a chunk of size 566, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 299, which is longer than the specified 1
Created a chunk of size 535, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 565, which is longer than the specified 1
Created a chunk of size 385, which is longer than the specified 1
Created a chunk of size 412, which is longer than the specified 1
Created a chunk of size 463, which is longer than the specified 1
Created a chunk of size 597, which is longer than the specified 1
Created a chunk of size 478, which is longer than the specified 1
Created a chunk of size 461, which is longer than the specified 1
Created a chunk of size 259, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 616, which is longer than the specified 1
Created a chunk of size 421, which is longer than the specified 1
Created a chunk of size 889, which is longer than the specified 1
Created a chunk of size 695, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 219, which is longer than the specified 1
Created a chunk of size 277, which is longer than the specified 1
Created a chunk of size 2010, which is longer than the specified 1
Created a chunk of size 175, which is longer than the specified 1
Created a chunk of size 481, which is longer than the specified 1
Created a chunk of size 302, which is longer than the specified 1
Created a chunk of size 522, which is longer than the specified 1
Created a chunk of size 649, which is longer than the specified 1
Created a chunk of size 778, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 550, which is longer than the specified 1
Created a chunk of size 1225, which is longer than the specified 1
Created a chunk of size 408, which is longer than the specified 1
Created a chunk of size 1186, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 1193, which is longer than the specified 1
Created a chunk of size 1059, which is longer than the specified 1
Created a chunk of size 246, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 878, which is longer than the specified 1
Created a chunk of size 286, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 419, which is longer than the specified 1
Created a chunk of size 210, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 528, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 340, which is longer than the specified 1
Created a chunk of size 901, which is longer than the specified 1
Created a chunk of size 1272, which is longer than the specified 1
Created a chunk of size 560, which is longer than the specified 1
Created a chunk of size 1637, which is longer than the specified 1
Created a chunk of size 438, which is longer than the specified 1
Created a chunk of size 251, which is longer than the specified 1
Created a chunk of size 779, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 516, which is longer than the specified 1
Created a chunk of size 960, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1132, which is longer than the specified 1
Created a chunk of size 170, which is longer than the specified 1
Created a chunk of size 1325, which is longer than the specified 1
Created a chunk of size 853, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 801, which is longer than the specified 1
Created a chunk of size 1121, which is longer than the specified 1
Created a chunk of size 838, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 734, which is longer than the specified 1
Created a chunk of size 1195, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 775, which is longer than the specified 1
Created a chunk of size 280, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 358, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 2012, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 1288, which is longer than the specified 1
Created a chunk of size 1231, which is longer than the specified 1
Created a chunk of size 729, which is longer than the specified 1
Created a chunk of size 750, which is longer than the specified 1
Created a chunk of size 447, which is longer than the specified 1
Created a chunk of size 1242, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 914, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 846, which is longer than the specified 1
Created a chunk of size 1128, which is longer than the specified 1
Created a chunk of size 1075, which is longer than the specified 1
Created a chunk of size 1320, which is longer than the specified 1
Created a chunk of size 363, which is longer than the specified 1
Created a chunk of size 2834, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 208, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 1006, which is longer than the specified 1
Created a chunk of size 715, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 2510, which is longer than the specified 1
Created a chunk of size 956, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 351, which is longer than the specified 1
Created a chunk of size 641, which is longer than the specified 1
Created a chunk of size 405, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 795, which is longer than the specified 1
Created a chunk of size 167, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 1424, which is longer than the specified 1
Created a chunk of size 1085, which is longer than the specified 1
Created a chunk of size 1146, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 790, which is longer than the specified 1
Created a chunk of size 297, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 876, which is longer than the specified 1
Created a chunk of size 808, which is longer than the specified 1
Created a chunk of size 1814, which is longer than the specified 1
Created a chunk of size 1830, which is longer than the specified 1
Created a chunk of size 1064, which is longer than the specified 1
Created a chunk of size 955, which is longer than the specified 1
Created a chunk of size 1182, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 288, which is longer than the specified 1
Created a chunk of size 1286, which is longer than the specified 1
Created a chunk of size 1644, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 1932, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 2008, which is longer than the specified 1
Created a chunk of size 2285, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 1003, which is longer than the specified 1
Created a chunk of size 579, which is longer than the specified 1
Created a chunk of size 290, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 1144, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 1483, which is longer than the specified 1
Created a chunk of size 223, which is longer than the specified 1
Created a chunk of size 1137, which is longer than the specified 1
Created a chunk of size 724, which is longer than the specified 1
Created a chunk of size 668, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 608, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 967, which is longer than the specified 1
Created a chunk of size 859, which is longer than the specified 1
Created a chunk of size 1034, which is longer than the specified 1
Created a chunk of size 191, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 497, which is longer than the specified 1
Created a chunk of size 652, which is longer than the specified 1
Created a chunk of size 350, which is longer than the specified 1
Created a chunk of size 735, which is longer than the specified 1
Created a chunk of size 527, which is longer than the specified 1
Created a chunk of size 1017, which is longer than the specified 1
Created a chunk of size 972, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 546, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 378, which is longer than the specified 1
Created a chunk of size 933, which is longer than the specified 1
Created a chunk of size 564, which is longer than the specified 1
Created a chunk of size 856, which is longer than the specified 1
Created a chunk of size 717, which is longer than the specified 1
Created a chunk of size 749, which is longer than the specified 1
Created a chunk of size 714, which is longer than the specified 1
Created a chunk of size 326, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 229, which is longer than the specified 1
Created a chunk of size 706, which is longer than the specified 1
Created a chunk of size 1914, which is longer than the specified 1
Created a chunk of size 397, which is longer than the specified 1
Created a chunk of size 487, which is longer than the specified 1
Created a chunk of size 622, which is longer than the specified 1
Created a chunk of size 561, which is longer than the specified 1
Created a chunk of size 558, which is longer than the specified 1
Created a chunk of size 388, which is longer than the specified 1
Created a chunk of size 231, which is longer than the specified 1
Created a chunk of size 427, which is longer than the specified 1
Created a chunk of size 418, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 168, which is longer than the specified 1
Created a chunk of size 626, which is longer than the specified 1
Created a chunk of size 2616, which is longer than the specified 1
Created a chunk of size 1580, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 996, which is longer than the specified 1
Created a chunk of size 849, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 338, which is longer than the specified 1
Created a chunk of size 1530, which is longer than the specified 1
Created a chunk of size 215, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 2032, which is longer than the specified 1
Created a chunk of size 398, which is longer than the specified 1
Created a chunk of size 1619, which is longer than the specified 1
Created a chunk of size 700, which is longer than the specified 1
Created a chunk of size 824, which is longer than the specified 1
Created a chunk of size 356, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 510, which is longer than the specified 1
Created a chunk of size 665, which is longer than the specified 1
Created a chunk of size 1284, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 217, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 1277, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1
Created a chunk of size 380, which is longer than the specified 1
Created a chunk of size 271, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 227, which is longer than the specified 1
Created a chunk of size 224, which is longer than the specified 1
Created a chunk of size 784, which is longer than the specified 1
Created a chunk of size 971, which is longer than the specified 1
Created a chunk of size 615, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 965, which is longer than the specified 1
Created a chunk of size 234, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1
Created a chunk of size 788, which is longer than the specified 1
Created a chunk of size 650, which is longer than the specified 1
Created a chunk of size 986, which is longer than the specified 1
Created a chunk of size 799, which is longer than the specified 1
Created a chunk of size 193, which is longer than the specified 1
Created a chunk of size 1163, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 203, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1

In [7]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

## Building vector databases

Creating document embeddings and storing in vector database

In [8]:
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
db_books = Chroma.from_documents(
    documents,
    embedding=embedding_model
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## Getting book recommendations using vector search

In [9]:
query = "a book about a young wizard who discovers his magical heritage and attends a school for wizards, where he makes friends and uncovers the truth about his past."
docs = db_books.similarity_search(query, k=10)
docs

[Document(id='1ac5af49-f184-4c94-be5e-2e6103199b70', metadata={'source': 'tagged_description.txt'}, page_content='"9780441010288 The first title in this bestselling series, now available in paperback, follows the adventures and training of young Merlin who is destined to become the greatest wizard of all time. Illustrations. Copyright © Libri GmbH. All rights reserved."'),
 Document(id='0ff7ef3d-5534-4170-b13d-10b43c69622a', metadata={'source': 'tagged_description.txt'}, page_content='"9780765357663 When thirteen-year-old Martin Anderson arrives at an alternative school for misfits and problem students, he falls in with a group of boys with psychic powers and discovers something surprising about himself. An ALA Best Book for Young Adults. Reprint."'),
 Document(id='6fc051ab-f1cb-4f0a-b99e-c2d8db8df48f', metadata={'source': 'tagged_description.txt'}, page_content='"9780571193783 A parable about love, literature and fanaticism. A young university student becomes obsessed with a magical book that delves into the dangerous natures of love and self. Abandoning his studies and his family, he goes with the beautiful Janan on a search for the meaning of the book\'s darker secrets."'),
 Document(id='b93c6be4-0cea-4b63-b1a4-b50580af25bf', metadata={'source': 'tagged_description.txt'}, page_content='9780452260115 This novel takes readers into a magical and richly peopled world which encompasses four generations of African American life. Copyright © Libri GmbH. All rights reserved.'),
 Document(id='5ab238d2-d592-42d1-9f41-678ffbe534f5', metadata={'source': 'tagged_description.txt'}, page_content='"9780141311883 Harry, bored with her sheltered life in the remote orange-growing colony of Daria, discovers magic in herself when she is kidnapped by a native king with mysterious powers. Newbery Medal Honor Book, 1983."'),
 Document(id='9937b7eb-1361-4164-983e-5eba510f36f3', metadata={'source': 'tagged_description.txt'}, page_content='"9780765313195 While enjoying a visit with an old friend in Tulsa, Oklahoma, Diana Tregarde discovers that a malevolent combination of sex and blood magic is behind relatively normal teenage jealousies and infatuations at the local high school, one ruled by Fay Harper, a powerful sorceress hundreds of years old who takes over the bodies of her own daughters to remain eternally young. Reprint. 15,000 first printing."'),
 Document(id='357f4312-8bae-45fe-866b-1e89c1ca5bd1', metadata={'source': 'tagged_description.txt'}, page_content='"9780812694550 Urging readers of the Harry Potter series to dig deeper than wizards, boggarts, and dementors, the authors of this unique guide collect the musings of seventeen philosophers on the series, who cover a wide range of Potter-related philosophical issues, including the difference between good and evil, the ethics of sorcery, and Aristotle\'s own school for wizards. Original."'),
 Document(id='a181ed5b-fdbe-4d96-9285-fd285ca337e2', metadata={'source': 'tagged_description.txt'}, page_content='"9780765312808 Having recently moved to a bohemian Toronto neighborhood, middle-aged entrepreneur Alan learns his next-door neighbor\'s struggle to conceal her wings and hides his own secrets about his unusual family, which includes Russian nesting doll brothers, one of whom is bent on revenge. By the author of Down and Out in the Magic Kingdom. Reprint. 20,000 first printing."'),
 Document(id='61d78f22-3827-41de-9b6e-325470f05c4e', metadata={'source': 'tagged_description.txt'}, page_content='"9780439411875 Failing out of magic school, Rhianna meets a wizard who realizes she is a Wild Talent, possessing a difficult-to-manage power, and when a dragon comes to town, it\'s up to Rhianna to master her craft or face certain doom."'),
 Document(id='999a4a9a-e25a-46a8-8fbf-e5ffc26a247f', metadata={'source': 'tagged_description.txt'}, page_content='"9780747546245 The summer holidays are dragging on and Harry Potter can\'t wait for the start of the school year. It is his fourth year at Hogwarts School of Witchcraft and Wizardry and there are spells to be learnt and (unluckily) Potions and Divination lessons to be attended. But Harry can\'t know that the atmosphere is darkening around him, and his worst enemy is preparing a fate that it seems will be inescapable . . . With characteristic wit, fast-paced humour and marvellous emotional depth, J.K. Rowling has proved herself yet again to be a master story-teller."')]

In [10]:
books[books["isbn13"]== int(docs[0].page_content.split()[0].strip('"'))]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,embedding_input,book_id
2227,9780441010288,0441010288,The Lost Years of Merlin,T. A. Barron,Fiction,http://books.google.com/books/content?id=T5E1z...,"The first title in this bestselling series, no...",2002.0,3.98,304.0,12114.0,The Lost Years of Merlin,9780441010288 The first title in this bestsell...,The Lost Years of Merlin The first title in th...,9780441010288

In [11]:
def retrieve_semantic_recommendaions(
        query:str,
        top_k:int=10
)-> pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)
    book_list = []
    # basic loop
    # for i in range(0, len(recs)):
    #     book_list += [int(recs[i].page_content.strip('"').split()[0])]
    
    # List comprehension
    # book_list = [int(recs[i].page_content.strip('"').split()[0]) for i in range(0, len(recs))]
    
    # build in: map function
    book_list = list(map(lambda x: int(x.page_content.strip('"').split()[0]), recs))

    return books[books["isbn13"].isin(book_list)].head(top_k)

In [12]:
retrieve_semantic_recommendaions("a book about a young wizard who discovers his magical heritage and attends a school for wizards, where he makes friends and uncovers the truth about his past.", top_k=10)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,embedding_input,book_id
102,9780060177249,0060177241,The thief of always,Clive Barker,Fiction,http://books.google.com/books/content?id=jKsrA...,After a mysterious stranger promises to end hi...,1992.0,4.19,225.0,22123.0,The thief of always: a fable,9780060177249 After a mysterious stranger prom...,The thief of always: a fable After a mysteriou...,9780060177249
146,9780060556501,0060556501,"The Lion, the Witch and the Wardrobe (picture ...",C. S. Lewis,Juvenile Fiction,http://books.google.com/books/content?id=FlSpp...,Narnia: A magical land full of wonder and exci...,2004.0,4.19,48.0,5012.0,"The Lion, the Witch and the Wardrobe (picture ...",9780060556501 Narnia: A magical land full of w...,"The Lion, the Witch and the Wardrobe (picture ...",9780060556501
256,9780060845247,0060845244,"The Lion, the Witch and the Wardrobe Read-Alou...",C. S. Lewis;Pauline Baynes,Juvenile Fiction,http://books.google.com/books/content?id=deiyG...,Four English school children enter the magic l...,2005.0,4.21,189.0,56.0,"The Lion, the Witch and the Wardrobe Read-Alou...",9780060845247 Four English school children ent...,"The Lion, the Witch and the Wardrobe Read-Alou...",9780060845247
266,9780060880125,0060880120,How to Be Popular,Meg Cabot,Juvenile Fiction,http://books.google.com/books/content?id=uRsWy...,Sixteen-year-old Steph Landry finds an old boo...,2006.0,3.54,288.0,19183.0,How to Be Popular,9780060880125 Sixteen-year-old Steph Landry fi...,How to Be Popular Sixteen-year-old Steph Landr...,9780060880125
397,9780062512796,006251279X,The Pilgrimage,Paulo Coelho;Alan R. Clarke,Fiction,http://books.google.com/books/content?id=atdJc...,"Previously published as The Diary of a Magus, ...",1995.0,3.65,272.0,878.0,The Pilgrimage,9780062512796 Previously published as The Diar...,The Pilgrimage Previously published as The Dia...,9780062512796
771,9780141303352,0141303352,Mr Majeika and the School Trip,Humphrey Carpenter,Juvenile Fiction,http://books.google.com/books/content?id=YJ8eq...,"More amazing adventures with Mr Majeika, the e...",1999.0,3.81,89.0,45.0,Mr Majeika and the School Trip,9780141303352 More amazing adventures with Mr ...,Mr Majeika and the School Trip More amazing ad...,9780141303352
779,9780141311883,0141311886,The Blue Sword,Robin McKinley,NaN,http://books.google.com/books/content?id=nDW2H...,"Harry, bored with her sheltered life in the re...",2001.0,4.23,272.0,286.0,The Blue Sword,"9780141311883 Harry, bored with her sheltered ...","The Blue Sword Harry, bored with her sheltered...",9780141311883
1184,9780312186883,0312186886,Human Croquet,Kate Atkinson,Fiction,http://books.google.com/books/content?id=qGNmj...,A dark yet moving exploration of a young girl'...,1999.0,3.71,352.0,6602.0,Human Croquet: A Novel,9780312186883 A dark yet moving exploration of...,Human Croquet: A Novel A dark yet moving explo...,9780312186883
1221,9780312316136,0312316135,The Gatekeeper,Terry Eagleton,Biography & Autobiography,http://books.google.com/books/content?id=93Q0Q...,An Oxford scholar and author of The Truth Abou...,2003.0,3.80,192.0,94.0,The Gatekeeper: A Memoir,9780312316136 An Oxford scholar and author of ...,The Gatekeeper: A Memoir An Oxford scholar and...,9780312316136
1280,9780312873110,0312873115,The Land of Laughs,Jonathan Carroll,Fiction,http://books.google.com/books/content?id=OUIAm...,Have you ever loved a magical book above all o...,2001.0,3.90,256.0,4218.0,The Land of Laughs: A Novel,9780312873110 Have you ever loved a magical bo...,The Land of Laughs: A Novel Have you ever love...,9780312873110

## Simplifying categories

In [41]:
category_mapping = {
    'Fiction': 'Fiction',
    'Juvenile Fiction': "Children's Fiction",
    'Biography & Autobiography': 'Nonfiction',
    'History': 'Nonfiction',
    'Literary Criticism': 'Nonfiction',
    'Philosophy': 'Nonfiction',
    'Religion': 'Nonfiction',
    'Comics & Graphic Novels': 'Fiction',
    'Drama': 'Fiction',
    'Juvenile Nonfiction': "Children's Nonfiction",
    'Science': 'Nonfiction',
    'Poetry': 'Fiction',
}

books["simple_categories"] = books["categories"].map(category_mapping)

In [14]:
books[~(books['simple_categories'].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,embedding_input,book_id,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Gilead A NOVEL THAT READERS and critics have b...,9780002005883,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...","Rage of angels A memorable, mesmerizing heroin...",9780006178736,Fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,Warhost of Vastmark,9780006482079 Tricked once more by his wily ha...,Warhost of Vastmark Tricked once more by his w...,9780006482079,Fiction
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006 Joe and his parents are enjoying...,Ocean Star Express Joe and his parents are enj...,9780006646006,Children's Fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,Taken at the Flood,9780007121014 A Few Weeks After Marrying An At...,Taken at the Flood A Few Weeks After Marrying ...,9780007121014,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,"""Cornell Woolrich's novels define the essence ...",2007.0,3.77,344.0,680.0,Night Has a Thousand Eyes,"9781933648279 ""Cornell Woolrich's novels defin...","Night Has a Thousand Eyes ""Cornell Woolrich's ...",9781933648279,Fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,Coin Locker Babies,9784770028969 Rescued from the lockers in whic...,Coin Locker Babies Rescued from the lockers in...,9784770028969,Fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,"Cry, the Peacock This book is the story of a y...",9788122200850,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,I Am that: Talks with Sri Nisargadatta Maharaj...,9788185300535,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,The Berlin Phenomenology Since the three volum...,9789027712059,Nonfiction

## Zero-shot classification

In [15]:
from transformers import pipeline

fiction_categories=['Fiction', 'Nonfiction']
pipe = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=-1)
# result = classifier(some_description, candidate_labels=["fiction", "nonfiction"])

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

In [16]:
sequence = books.loc[books['simple_categories']=="Fiction", 'description'].reset_index(drop=True)[0]

In [39]:
pipe(sequence, fiction_categories)

{'sequence': "Wisdom to Create a Life of Passion, Purpose, and Peace This inspiring tale provides a step-by-step approach to living with greater courage, balance, abundance, and joy. A wonderfully crafted fable, The Monk Who Sold His Ferrari tells the extraordinary story of Julian Mantle, a lawyer forced to confront the spiritual crisis of his out-of-balance life. On a life-changing odyssey to an ancient culture, he discovers powerful, wise, and practical lessons that teach us to: Develop joyful thoughts Follow our life's mission and calling Cultivate self-discipline and act courageously Value time as our most important commodity Nourish our relationships, and – live fully, one day at a time A FABLE ABOUT FULFILLING YOUR DREAMS AND REACHING YOUR DESTINY",
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.9869533777236938, 0.013046618551015854]}

In [18]:
import numpy as np

max_index=np.argmax(pipe(sequence, fiction_categories)['scores'])
max_label=pipe(sequence, fiction_categories)['labels'][max_index]
max_label

'Fiction'

In [19]:
def generate_prediction(sequence:str, category)->str:
    predictions = pipe(sequence, category)
    max_index=np.argmax(predictions['scores'])
    max_label=predictions['labels'][max_index]
    return max_label

In [20]:

actual_cats = []
predicted_cats =[]

In [21]:
from tqdm import tqdm

for i in tqdm(range(0, 300)):
    sequence = books.loc[books['simple_categories']=="Fiction",'description'].reset_index(drop=True)[i]
    predicted_cats += [generate_prediction(sequence, fiction_categories)]
    actual_cats+=["Fiction"]

100%|██████████| 300/300 [19:51<00:00,  3.97s/it]

In [22]:
for i in tqdm(range(0, 300)):
    sequence = books.loc[books['simple_categories']=='Nonfiction', 'description'].reset_index(drop=True)[i]
    predicted_cats += [generate_prediction(sequence, fiction_categories)]
    actual_cats+=["Nonfiction"]

100%|██████████| 300/300 [15:46<00:00,  3.16s/it]

In [23]:
predictions_df = pd.DataFrame({'actual_categories': actual_cats, 'predicted_categories': predicted_cats})

In [24]:
predictions_df['correct_prediction'] = (
    np.where(predictions_df['actual_categories'] == predictions_df['predicted_categories'], 1, 0)   
)
predictions_df['correct_prediction'].sum()/len(predictions_df)

np.float64(0.7783333333333333)

In [25]:
isbns = []
predicted_cats=[]

missing_cats = books.loc[books['simple_categories'].isna(), ['isbn13','description']].reset_index(drop=True)

In [26]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats.loc[i, 'description']
    predicted_cats += [generate_prediction(sequence, fiction_categories)]
    isbns += [missing_cats.loc[i, 'isbn13']]

100%|██████████| 1454/1454 [1:13:44<00:00,  3.04s/it]

In [27]:

missing_predicted_df= pd.DataFrame({'isbn13':isbns, 'predicted_cats':predicted_cats})

In [43]:
len(isbns), len(predicted_cats), len(missing_cats)

(1454, 1454, 1454)

In [44]:
missing_predicted_df.to_csv('missing_predicted.csv', index=False)

In [47]:
books =pd.merge(books, missing_predicted_df, on='isbn13', how='left')
prediction_cols = [
    col for col in books.columns
    if col == "predicted_cats" or col.startswith("predicted_cats_")
]
books = books.drop(columns=prediction_cols)

books = books.merge(missing_predicted_df, on="isbn13", how="left")
books["simple_categories"] = books["simple_categories"].fillna(
    books["predicted_cats"]
)
books = books.drop(columns="predicted_cats")

In [48]:
books[books['categories'].str.lower().isin([
    'romance',
    'science fiction',
    'fantasy',
    'scifi',
    'fantasy',
    'horror',
    'mystery',
    'thriller',
    'comedy',
    'crime',
    'historical'
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,embedding_input,book_id,simple_categories
24,9780006513087,0006513085,Gravity,Tess Gerritsen,Science fiction,http://books.google.com/books/content?id=KI66c...,Emma Watson a research physician has been trai...,2004.0,4.04,342.0,8024.0,Gravity,9780006513087 Emma Watson a research physician...,Gravity Emma Watson a research physician has b...,9780006513087,Nonfiction
475,9780099410355,0099410354,Traitor,Matthew Woodring Stover,Science fiction,http://books.google.com/books/content?id=VbICO...,"From the depths of catastrophe, a glimmer of h...",2002.0,4.00,320.0,6765.0,Traitor,"9780099410355 From the depths of catastrophe, ...","Traitor From the depths of catastrophe, a glim...",9780099410355,Fiction
478,9780099422341,0099422344,Yeats is Dead!,Joseph O'Connor,Comedy,http://books.google.com/books/content?id=DrE3I...,"In aid of Amnesty International, this is a bri...",2002.0,3.39,298.0,34.0,Yeats is Dead!: A Novel by Fifteen Irish Writers,"9780099422341 In aid of Amnesty International,...",Yeats is Dead!: A Novel by Fifteen Irish Write...,9780099422341,Fiction
491,9780099446729,0099446723,Blackwood Farm,Anne Rice,Horror,http://books.google.com/books/content?id=cIn8T...,"Lestat Is Back, Saviour And Demon, Presiding O...",2003.0,3.86,774.0,26145.0,Blackwood Farm,"9780099446729 Lestat Is Back, Saviour And Demo...","Blackwood Farm Lestat Is Back, Saviour And Dem...",9780099446729,Fiction
1090,9780261102422,0261102427,The Silmarillion,John Ronald Reuel Tolkien,Fantasy,http://books.google.com/books/content?id=22ePu...,Tolkien's Silmarillion is the core work of the...,1999.0,3.91,384.0,253.0,The Silmarillion,9780261102422 Tolkien's Silmarillion is the co...,The Silmarillion Tolkien's Silmarillion is the...,9780261102422,Fiction
1435,9780340837955,0340837950,Stranger in a Strange Land,Robert A. Heinlein,Science fiction,http://books.google.com/books/content?id=ZQhiP...,"Epic, entertaining, Stranger in a Strange Land...",2005.0,3.92,672.0,563.0,Stranger in a Strange Land,"9780340837955 Epic, entertaining, Stranger in ...","Stranger in a Strange Land Epic, entertaining,...",9780340837955,Fiction
1439,9780345251220,0345251229,Visions from Nowhere,William Arrow,Science fiction,NaN,"The first novel in the series, ""Return to the ...",1976.0,3.23,183.0,10.0,Visions from Nowhere,"9780345251220 The first novel in the series, ""...",Visions from Nowhere The first novel in the se...,9780345251220,Fiction
2845,9780575075597,0575075597,Replay,Ken Grimwood,Fantasy,http://books.google.com/books/content?id=9vmNP...,At forty-three Jeff Winston is tired of his lo...,2005.0,4.16,272.0,412.0,Replay,9780575075597 At forty-three Jeff Winston is t...,Replay At forty-three Jeff Winston is tired of...,9780575075597,Fiction
2860,9780590254762,0590254766,"The lion, the witch and the wardrobe",Clive Staples Lewis,Fantasy,NaN,Four English school children enter the magic l...,1995.0,4.21,189.0,860.0,"The lion, the witch and the wardrobe",9780590254762 Four English school children ent...,"The lion, the witch and the wardrobe Four Engl...",9780590254762,Nonfiction
3288,9780739423851,0739423851,Wizard's Castle,Diana Wynne Jones,Fantasy,http://books.google.com/books/content?id=hB7hA...,Howl's moving castle - Eldest of three sisters...,2002.0,4.44,376.0,439.0,Wizard's Castle,9780739423851 Howl's moving castle - Eldest of...,Wizard's Castle Howl's moving castle - Eldest ...,9780739423851,Fiction
3289,9780739439708,0739439707,Time Quartet,Madeleine L'Engle,Science fiction,NaN,"Blending magic with quantum physics, Madeleine...",2003.0,4.35,646.0,165.0,Time Quartet,9780739439708 Blending magic with quantum phys...,Time Quartet Blending magic with quantum physi...,9780739439708,Fiction
3563,9780760728505,076072850X,"20,000 Leagues Under the Sea",Jules Verne,Science fiction,NaN,Retells the adventures of a French professor a...,2002.0,3.88,394.0,135778.0,"20,000 Leagues Under the Sea",9780760728505 Retells the adventures of a Fren...,"20,000 Leagues Under the Sea Retells the adven...",9780760728505,Fiction
4483,9781416502043,1416502041,The Voyage of the Jerle Shannara Trilogy,Terry Brooks,Fantasy,http://books.google.com/books/content?id=jqVsA...,When the body of a half-drowned elf is found f...,2004.0,4.26,1260.0,84.0,The Voyage of the Jerle Shannara Trilogy,9781416502043 When the body of a half-drowned ...,The Voyage of the Jerle Shannara Trilogy When ...,9781416502043,Fiction
4979,9781841494081,1841494089,The Darkness that Comes Before,R. Scott Bakker,Fantasy,http://books.google.com/books/content?id=BG8qG...,A score of centuries has passed since the Firs...,2005.0,3.79,638.0,317.0,The Darkness that Comes Before,9781841494081 A score of centuries has passed ...,The Darkness that Comes Before A score of cent...,9781841494081,Nonfiction
5040,9781857231359,185723135X,Use of Weapons,Iain Banks,Science fiction,NaN,The man known as Cheradenine Zakalwe was one o...,1992.0,4.19,411.0,30779.0,Use of Weapons,9781857231359 The man known as Cheradenine Zak...,Use of Weapons The man known as Cheradenine Za...,9781857231359,Nonfiction
5057,9781857989342,1857989341,The Gods Themselves,Isaac Asimov,Science fiction,http://books.google.com/books/content?id=8ClIP...,"In the year 2100, mankind on Earth, settlers i...",2000.0,4.09,288.0,41304.0,The Gods Themselves,"9781857989342 In the year 2100, mankind on Ear...","The Gods Themselves In the year 2100, mankind ...",9781857989342,Fiction

In [49]:
books.to_csv('books_with_categories.csv', index=False)